# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'jekyll'
gem 'jekyll-seo-tag'
gem 'jekyll-sass-converter'
gem 'jekyll-sitemap'
gem 'sass-embedded'
gem 'google-protobuf'
gem 'html-proofer'
gem 'w3c_validators'
gem 'nokogiri'
gem 'parallel'
gem 'rainbow'
gem 'typhoeus'
gem 'yell'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-github'
gem 'json'
gem 'racc'
gem 'ethon'
gem 'language_server-protocol'
gem 'parser'
gem 'regexp_parser'
gem 'rubocop-ast'
gem 'ruby-progressbar'
gem 'activesupport'
gem 'rack'
gem 'ast'
gem 'base64'
gem 'connection_pool'
gem 'drb'
gem 'logger'
gem 'minitest'
gem 'securerandom'
gem 'tzinfo'
gem 'csv'
gem 'wdm'